App/views.py
from random import randint

from flask import Blueprint, render_template, request, redirect, url_for, session, make_response, jsonify, flash
from flask_login import login_user

from App.models import *
from App.forms import RegisterForm
from App.verifycode import vc
from App.sms import sms

bp = Blueprint('bp', __name__)


# 1.首页
@bp.route("/")
def home():
    articles = Article.query.all()
    user = User.query.first()
    print(user.username)

    three_articles = Article.query.order_by(-Article.create_time).all()[:3]

    # articles = db.session.query(Article, Category).filter(Article.cid == Category.cid, Category.cid == aid).all()
    # categories = Category.query.all()
    return render_template("index.html", **locals())

# 2.1 tag跳转
@bp.route('/tag/')
@bp.route('/tag/<int:tid>')
def tag(tid=1):
    articles = db.session.query(Article, Tag).filter(Article.aid == Tag.aid, Tag.tid == tid).all()
    print(articles)
    article_num = len(articles)

    categories = Category.query.all()

    three_articles = Article.query.order_by(-Article.create_time).all()[:3]

    tags = Tag.query.all()
    print(tags)
    user = User.query.first()
    return render_template('blog.html', **locals())


# 2.分类的博客 cid
@bp.route("/list/")
@bp.route("/list/<int:cid>")
def list_article(cid=-1):
    if cid < 0:  # 查询默认
        category = Category.query.first()
        cid = category.cid

    articles = db.session.query(Article, Category).filter(Article.cid == Category.cid, Category.cid == cid).all()
    article_num = len(articles)
    print(articles)

    categories = Category.query.all()
    print(categories)
    for i in categories:
        print(i)
    user = User.query.first()

    # 最近3篇文章
    three_articles = Article.query.order_by(-Article.create_time).all()[:3]

    # 标签
    tags = Tag.query.all()
    # 改进 以下看是否有错
    # print(tags1)
    # for tag in tags1:
    #     print(tag)
    # article_tag = db.session.query(Article, Tag).filter(Article.aid == Tag.aid, Tag.tid == tid).all()
    return render_template("blog.html", **locals())

# 3.1 tag跳转
@bp.route('/tag1/')
@bp.route('/tag1/<int:tid1>')
def tag1(tid1=1):
    articles = db.session.query(Article, Tag).filter(Article.aid == Tag.aid, Tag.tid == tid1).all()
    print(articles)
    article_num = len(articles)

    categories = Category.query.all()

    three_articles = Article.query.order_by(-Article.create_time).all()[:3]

    tags1 = Tag.query.all()
    print(tags1)
    user = User.query.first()
    return render_template('post.html', **locals())


# 3.详细的一篇博客
@bp.route("/one/")
@bp.route("/one/<int:aid>")
def one_article(aid=-1):
    if aid < 0:  # 查询默认
        article = Article.query.first()
        aid = article.aid
    articles = db.session.query(Article).filter(Article.aid == aid).first()
    tags = db.session.query(Article, Tag).filter(Article.aid == Tag.aid, Article.aid == aid).first()
    print(tags)
    user = User.query.all()
    print(user)
    articles1 = Article.query.all()
    num = len(articles1)
    # print(articles1)
    mark = Mark.query.all()
    # 最近三篇
    three_articles = Article.query.order_by(-Article.create_time).all()[:3]
    # 分类
    categories = Category.query.all()
    print(categories)
    for i in categories:
        print(i)
    # 标签
    tags1 = Tag.query.all()
    print(categories)
    return render_template("post.html", **locals())


# 4.注册
@bp.route("/register/", methods=['GET', 'POST'])
def register_user():
    # 实例化表单类
    form = RegisterForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            # 验证
            username = request.values.get("username")
            password = request.values.get("password")
            phone = request.values.get("phone")
            print(username, password, phone)
            # 符合，存入。
            user = User(username=username, password=password, phone=phone)
            db.session.add(user)
            db.session.commit()
            # 去登陆
            return redirect(url_for('bp.login_user'))

    return render_template("register.htm", **locals())


# 图形验证码
@bp.route("/verify/")
def verify_code():
    result = vc.generate()
    # 把验证码字符串保存到session
    session['code'] = vc.code
    # 创建响应对象
    response = make_response(result)
    response.headers["Content-Type"] = "image/png"
    return response


# 短信验证码
@bp.route("/send/", methods=['GET', 'POST'])
def send_sms():
    phone = request.values.get('phone')
    print(phone)
    if phone:
        num = randint(10000, 99999)
        para = "{'number':'%d'}" % num
        session['sms'] = str(num)
        res = sms.send(phone, para)
        print(res, type(res))
        return jsonify({'code': 1, 'msg': '发送成功'})
    return jsonify({'code': 0, 'msg': '电话号码不存在'})


# 5.登录
@bp.route("/login/", methods=['GET', 'POST'])
def user_login():
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')
        print(username, password)
        us = User.query.filter(User.username == username, User.password == password).first()
        if us:
            login_user(us)
            return redirect(url_for('bp.home'))
        else:
            flash('用户名或密码错误!')
    return render_template('login.htm')

templates/blog.html
{% extends 'common/base.html' %}
{% block content %}
    <div class="container">
      <div class="row">
        <!-- Latest Posts -->
        <main class="posts-listing col-lg-8"> 
          <div class="container">
            <div class="row">
            {% for i in range(0,article_num,2) %}
              <!-- post -->
              <div class="post col-xl-6">
                <div class="post-thumbnail"><a href="{{ url_for('bp.one_article', aid=articles[i][0].aid) }}"><img src="{{ url_for('static', filename=articles[i][0].picture) }}" alt="..." class="img-fluid"></a></div>
                <div class="post-details">
                  <div class="post-meta d-flex justify-content-between">
                    <div class="date meta-last">{{articles[i][0].create_time}}</div>
                    <div class="category"><a href="#">Business</a></div>
                  </div><a href="{{ url_for('bp.one_article', aid=articles[i][0].aid) }}">
                    <h3 class="h4">{{ articles[i][0].title }}</h3></a>
                  <p class="text-muted">{{ articles[i][0].content }}</p>
                  <footer class="post-footer d-flex align-items-center"><a href="#" class="author d-flex align-items-center flex-wrap">
                      <div class="avatar"><img src="{{ url_for('static', filename=user.portrait) }}" alt="..." class="img-fluid"></div>
                      <div class="title"><span>{{ user.username }}</span></div></a>
                    <div class="date"><i class="icon-clock"></i>{{articles[i][0].create_time}}</div>
                    <div class="comments meta-last"><i class="icon-comment"></i>{{articles[i][0].replies}}</div>
                  </footer>
                </div>
              </div>

              {% if i < article_num - 1 %}
              <!-- post -->
              <div class="post col-xl-6">
                <div class="post-thumbnail"><a href="{{ url_for('bp.one_article', aid=articles[i+1][0].aid) }}"><img src="{{url_for('static', filename=articles[i+1][0].picture)}}" alt="..." class="img-fluid"></a></div>
                <div class="post-details">
                  <div class="post-meta d-flex justify-content-between">
                    <div class="date meta-last">{{articles[i+1][0].create_time}}</div>
                    <div class="category"><a href="#">Business</a></div>
                  </div><a href="{{ url_for('bp.one_article', aid=articles[i+1][0].aid) }}">
                    <h3 class="h4">{{ articles[i+1][0].title }}</h3></a>
                  <p class="text-muted">{{ articles[i+1][0].content }}</p>
                  <div class="post-footer d-flex align-items-center"><a href="#" class="author d-flex align-items-center flex-wrap">
                      <div class="avatar"><img src="{{ url_for('static', filename=user.portrait) }}" alt="..." class="img-fluid"></div>
                      <div class="title"><span>{{ user.username }}</span></div></a>
                    <div class="date"><i class="icon-clock"></i> {{ articles[i+1][0].create_time }}</div>
                    <div class="comments meta-last"><i class="icon-comment"></i>{{ articles[i+1][0].reples }}</div>
                  </div>
                </div>
              </div>
              {% else %}
                  <div class="post col-xl-6">
                <div class="post-thumbnail"><a href="post.html"><img src={{ url_for('static', filename=articles[i][0].picture) }}" alt="..." class="img-fluid"></a></div>
                <div class="post-details">
                  <div class="post-meta d-flex justify-content-between">
                    <div class="date meta-last">无</div>
                    <div class="category"><a href="#">Business</a></div>
                  </div><a href="post.html">
                    <h3 class="h4">无</h3></a>
                  <p class="text-muted">文章不存</p>
                  <div class="post-footer d-flex align-items-center"><a href="#" class="author d-flex align-items-center flex-wrap">
                      <div class="avatar"><img src={{ url_for('static',filename=user.portrait) }} alt="..." class="img-fluid"></div>
                      <div class="title"><span>{{ user.username}}</span></div></a>
                    <div class="date"><i class="icon-clock"></i> </div>
                    <div class="comments meta-last"><i class="icon-comment"></i>0</div>
                  </div>
                </div>
              </div>
                {% endif %}
            {% endfor %}
            <!-- Pagination -->
            <nav aria-label="Page navigation example">
              <ul class="pagination pagination-template d-flex justify-content-center">
                <li class="page-item"><a href="#" class="page-link"> <i class="fa fa-angle-left"></i></a></li>
                <li class="page-item"><a href="#" class="page-link active">1</a></li>
                <li class="page-item"><a href="#" class="page-link">2</a></li>
                <li class="page-item"><a href="#" class="page-link">3</a></li>
                <li class="page-item"><a href="#" class="page-link"> <i class="fa fa-angle-right"></i></a></li>
              </ul>
            </nav>
          </div>
        </main>
        <aside class="col-lg-4">
          <!-- Widget [Search Bar Widget]-->
          <div class="widget search">
            <header>
              <h3 class="h6">Search the blog</h3>
            </header>
            <form action="#" class="search-form">
              <div class="form-group">
                <input type="search" placeholder="What are you looking for?">
                <button type="submit" class="submit"><i class="icon-search"></i></button>
              </div>
            </form>
          </div>
          <!-- Widget [Latest Posts Widget]        -->
          <div class="widget latest-posts">
            <header>
              <h3 class="h6">Latest Posts</h3>
            </header>
              {% for article in three_articles %}
            <div class="blog-posts"><a href="{{ url_for('bp.one_article', aid=article.aid) }}">

                <div class="item d-flex align-items-center">
                  <div class="image"><img src="{{ url_for('static',filename=article.picture) }}" alt="..." class="img-fluid"></div>
                  <div class="title"><strong>{{ article.title }}</strong>
                    <div class="d-flex align-items-center">
                      <div class="views"><i class="icon-eye"></i> {{ article.hits }}</div>
                      <div class="comments"><i class="icon-comment"></i>{{ article.replies }}</div>
                    </div>
                  </div>
                </div></a><a href="#">
                {% endfor %}
            </div>
          <!-- Widget [Categories Widget]-->
          <div class="widget categories">
            <header>
              <h3 class="h6">分类</h3>
            </header>
              {% for category in categories %}
             <div class="item d-flex justify-content-between"><a href="{{ url_for('bp.list_article',cid=category.cid) }}">{{category.name}}</a><span>{{ category.num }}</span></div>
             {% endfor %}
          </div>
          <!-- Widget [Tags Cloud Widget]-->
          <div class="widget tags">       
            <header>
              <h3 class="h6">Tags</h3>
            </header>
            <ul class="list-inline">
                {% for tag in tags %}
              <li class="list-inline-item"><a href="{{ url_for('bp.tag',tid=tag.tid) }}" class="tag">{{ tag.name }}</a></li>
                {% endfor %}
            </ul>
          </div>
        </aside>
      </div>
    </div>
{% endblock %}

templates/post.html
{% extends 'common/base.html' %}
{% block content %}
<div class="container">
          <!-- Navbar Brand -->
          <div class="navbar-header d-flex align-items-center justify-content-between">
            <!-- Navbar Brand --><a href="index.html" class="navbar-brand">Bootstrap Blog</a>
            <!-- Toggle Button-->
            <button type="button" data-toggle="collapse" data-target="#navbarcollapse" aria-controls="navbarcollapse" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler"><span></span><span></span><span></span></button>
          </div>
          <!-- Navbar Menu -->
          <div id="navbarcollapse" class="collapse navbar-collapse">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item"><a href="index.html" class="nav-link ">Home</a>
              </li>
              <li class="nav-item"><a href="blog.html" class="nav-link ">Blog</a>
              </li>
              <li class="nav-item"><a href="post.html" class="nav-link active ">Post</a>
              </li>
              <li class="nav-item"><a href="#" class="nav-link ">Contact</a>
              </li>
            </ul>
            <div class="navbar-text"><a href="#" class="search-btn"><i class="icon-search-1"></i></a></div>
            <ul class="langs navbar-text"><a href="#" class="active">EN</a><span>           </span><a href="#">ES</a></ul>
          </div>
        </div>
      </nav>
    </header>
    <div class="container">
      <div class="row">
        <!-- Latest Posts -->
        <main class="post blog-post col-lg-8">
          <div class="container">
            <div class="post-single">
              <div class="post-thumbnail"><img src="{{ url_for('static', filename=articles.picture) }}" alt="..." class="img-fluid"></div>
              <div class="post-details">
                <div class="post-meta d-flex justify-content-between">
                  <div class="category"><a href="#">{{ tags[1].name }}</a><a href="#"></a></div>
                </div>
                <h1>{{ articles.title }}<a href="#"><i class="fa fa-bookmark-o"></i></a></h1>
                <div class="post-footer d-flex align-items-center flex-column flex-sm-row"><a href="#" class="author d-flex align-items-center flex-wrap">
                    <div class="avatar"><img src="{{ url_for('static', filename=user[0].portrait) }}" alt="..." class="img-fluid"></div>
                    <div class="title"><span>{{ user[0].username}}</span></div></a>
                  <div class="d-flex align-items-center flex-wrap">
                    <div class="date"><i class="icon-clock"></i>{{ articles.create_time }}</div>
                    <div class="views"><i class="icon-eye"></i>9</div>
                    <div class="comments meta-last"><i class="icon-comment"></i>3</div>
                  </div>
                </div>
                <div class="post-body">
                  <p class="lead">{{ articles.content }}</p>
                  <p>{{ articles.content }}</p>
                  <p> <img src="{{ url_for('static', filename=articles.picture) }}" alt="..." class="img-fluid"></p>
                  <h3>{{ articles.content }}</h3>
                  <p>{{ articles.content }}</p>
                  <blockquote class="blockquote">
                    <p>{{ articles.content }}</p>
                    <footer class="blockquote-footer">{{ articles.content }}
                      <cite title="Source Title"></cite>
                    </footer>
                  </blockquote>
                  <p>{{ articles.content }}</p>
                </div>
                <div class="post-tags"><a href="#" class="tag">{{ tags[1].name }}</a><a href="#" class="tag"></a><a href="#" class="tag"></a><a href="#" class="tag"></a></div>
                <div class="posts-nav d-flex justify-content-between align-items-stretch flex-column flex-md-row">
                    {% if aid > 1 %}
                    <a href="{{ url_for('bp.one_article', aid = aid-1)}}" class="prev-post text-left d-flex align-items-center">
                    <div class="icon prev"><i class="fa fa-angle-left"></i></div>
                    <div class="text"><strong class="text-primary">Previous Post </strong>
                      <h6>articles</h6>
                    </div></a>
                    {% else %}
                    <a href="{{ url_for('bp.one_article', aid = aid)}}" class="prev-post text-left d-flex align-items-center">
                    <div class="icon prev"><i class="fa fa-angle-left"></i></div>
                    <div class="text"><strong class="text-primary">Previous Post </strong>
                      <h6>已经是第一篇</h6>
                    </div></a>
                    {% endif %}
                    {% if aid >= num %}
                    <a href="{{ url_for('bp.one_article', aid = aid)}}" class="next-post text-right d-flex align-items-center justify-content-end">
                    <div class="text"><strong class="text-primary">Next Post </strong>
                      <h6>已经是最后一篇</h6>
                    </div>
                    <div class="icon next"><i class="fa fa-angle-right">   </i></div></a>
                    {% else %}
                    <a href="{{ url_for('bp.one_article', aid = aid + 1)}}" class="next-post text-right d-flex align-items-center justify-content-end">
                    <div class="text"><strong class="text-primary">Next Post </strong>
                      <h6>article</h6>
                    </div>
                    <div class="icon next"><i class="fa fa-angle-right">   </i></div></a>
                    {% endif %}
                </div>
                <div class="post-comments">
                  <header>
                    <h3 class="h6">Post Comments<span class="no-of-comments">(3)</span></h3>
                  </header>
                  <div class="comment">
                    <div class="comment-header d-flex justify-content-between">
                      <div class="user d-flex align-items-center">
                        <div class="image"><img src="{{ url_for('static', filename=user[1].portrait) }}" alt="..." class="img-fluid rounded-circle"></div>
                        <div class="title"><strong>{{ user[1].username }}</strong><span class="date">{{ mark[0].create_time }}</span></div>
                      </div>
                    </div>
                    <div class="comment-body">
                      <p>{{ mark[0].content }}</p>
                    </div>
                  </div>
                  <div class="comment">
                    <div class="comment-header d-flex justify-content-between">
                      <div class="user d-flex align-items-center">
                        <div class="image"><img src="{{ url_for('static', filename=user[1].portrait) }}" alt="..." class="img-fluid rounded-circle"></div>
                        <div class="title"><strong>{{ user[1].username }}</strong><span class="date">{{ mark[1].create_time }}</span></div>
                      </div>
                    </div>
                    <div class="comment-body">
                      <p> {{ mark[1].content }}</p>
                    </div>
                  </div>
                  <div class="comment">
                    <div class="comment-header d-flex justify-content-between">
                      <div class="user d-flex align-items-center">
                        <div class="image"><img src="{{ url_for('static', filename=user[1].portrait) }}" alt="..." class="img-fluid rounded-circle"></div>
                        <div class="title"><strong>John Doe</strong><span class="date">{{ mark[1].create_time }}</span></div>
                      </div>
                    </div>
                    <div class="comment-body">
                      <p>{{ mark[2].content }}</p>
                    </div>
                  </div>
                </div>
                <div class="add-comment">
                  <header>
                    <h3 class="h6">Leave a reply</h3>
                  </header>
                  <form action="#" class="commenting-form">
                    <div class="row">
                      <div class="form-group col-md-6">
                        <input type="text" name="username" id="username" placeholder="Name" class="form-control">
                      </div>
                      <div class="form-group col-md-6">
                        <input type="email" name="username" id="useremail" placeholder="Email Address (will not be published)" class="form-control">
                      </div>
                      <div class="form-group col-md-12">
                        <textarea name="usercomment" id="usercomment" placeholder="Type your comment" class="form-control"></textarea>
                      </div>
                      <div class="form-group col-md-12">
                        <button type="submit" class="btn btn-secondary">Submit Comment</button>
                      </div>
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </main>
        <aside class="col-lg-4">
          <!-- Widget [Search Bar Widget]-->
          <div class="widget search">
            <header>
              <h3 class="h6">Search the blog</h3>
            </header>
            <form action="#" class="search-form">
              <div class="form-group">
                <input type="search" placeholder="What are you looking for?">
                <button type="submit" class="submit"><i class="icon-search"></i></button>
              </div>
            </form>
          </div>
          <!-- Widget [Latest Posts Widget]        -->
          <div class="widget latest-posts">
            <header>
              <h3 class="h6">Latest Posts</h3>
            </header>
            <div class="blog-posts"><a href="{{ url_for('bp.one_article', aid=three_articles[0].aid) }}">
                <div class="item d-flex align-items-center">
                  <div class="image"><img src="{{ url_for('static',filename=three_articles[0].picture) }}" alt="..." class="img-fluid"></div>
                  <div class="title"><strong>{{ three_articles[0].title }}</strong>
                    <div class="d-flex align-items-center">
                      <div class="views"><i class="icon-eye"></i>9</div>
                      <div class="comments"><i class="icon-comment"></i>3</div>
                    </div>
                  </div>
                </div></a><a href="{{ url_for('bp.one_article', aid=three_articles[1].aid) }}">
                <div class="item d-flex align-items-center">
                  <div class="image"><img src="{{ url_for('static',filename=three_articles[1].picture) }}" alt="..." class="img-fluid"></div>
                  <div class="title"><strong>{{ three_articles[1].title }}</strong>
                    <div class="d-flex align-items-center">
                      <div class="views"><i class="icon-eye"></i>9</div>
                      <div class="comments"><i class="icon-comment"></i>3</div>
                    </div>
                  </div>
                </div></a><a href="{{ url_for('bp.one_article', aid=three_articles[2].aid) }}">
                <div class="item d-flex align-items-center">
                  <div class="image"><img src="{{ url_for('static',filename=three_articles[2].picture) }}" alt="..." class="img-fluid"></div>
                  <div class="title"><strong>{{ three_articles[2].title }}</strong>
                    <div class="d-flex align-items-center">
                      <div class="views"><i class="icon-eye"></i>9</div>
                      <div class="comments"><i class="icon-comment"></i>3</div>
                    </div>
                  </div>
                </div></a></div>
          </div>
          <!-- Widget [Categories Widget]-->
          <div class="widget categories">
            <header>
              <h3 class="h6">分类</h3>
            </header>
              {% for i in categories %}
            <div class="item d-flex justify-content-between"><a href="{{ url_for('bp.list_article',cid=i.cid) }}">{{ i.name }}</a><span>{{ i.num }}</span></div>
              {% endfor %}
          </div>
          <!-- Widget [Tags Cloud Widget]-->
          <div class="widget tags">
            <header>
              <h3 class="h6">Tags</h3>
            </header>
            <ul class="list-inline">
                {% for tag in tags1 %}
              <li class="list-inline-item"><a href="{{ url_for('bp.tag',tid=tag.tid) }}" class="tag">{{ tag.name }}</a></li>
                {% endfor %}
            </ul>
          </div>
        </aside>
      </div>
    </div>
{% endblock %}